name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python<=3.12.3
  - mlflow==2.20.1
  - numpy<3
  - pandas<3
  - scikit-learn>=0.24.1,<1.6.2
  - pip
  - pip:
    - -r requirements.txt